<Tarefas>:
	orientation: "vertical"
	ScrollView:
		BoxLayout:
			orientation: "vertical"
			size_hint_y: None
			height: self.minimum_height
			id:box
	BoxLayout:
		size_hint_y: None
		height: 60
		TextInput:
			id: texto
		Button:
			text: "+"
			size_hint_x: None
			width: 60
			on_release: root.addWidget()
<Tarefa>:
	size_hint_y: None
	height: 200
	Label:
		id: label
	Button:
		text: "X"
		size_hint_x: None
		width: 60
		on_release: app.root.ids.box.remove_widget(root)#ou self.parent